package org.platform.sns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Jul 26 11:49:08 CEST 2013
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://interfaces.base.snps.osgi.org/", name = "iWebIntegrationInterfacePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IWebIntegrationInterfacePortType {

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "sayhello", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.Sayhello")
    @ResponseWrapper(localName = "sayhelloResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.SayhelloResponse")
    @WebMethod
    public java.lang.String sayhello();

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "buildVirtualSensor", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.BuildVirtualSensor")
    @ResponseWrapper(localName = "buildVirtualSensorResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.BuildVirtualSensorResponse")
    @WebMethod
    public java.lang.String buildVirtualSensor(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        org.platform.sns.ArrayOfString arg0,
        @WebParam(name = "arg1", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "sendCommand", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.SendCommand")
    @ResponseWrapper(localName = "sendCommandResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.SendCommandResponse")
    @WebMethod
    public java.lang.String sendCommand(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        org.platform.sns.ArrayOfString arg1,
        @WebParam(name = "arg2", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "DiscoverySensorsAndMeasurements", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.DiscoverySensorsAndMeasurements")
    @ResponseWrapper(localName = "DiscoverySensorsAndMeasurementsResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.DiscoverySensorsAndMeasurementsResponse")
    @WebMethod(operationName = "DiscoverySensorsAndMeasurements")
    public java.lang.String discoverySensorsAndMeasurements(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg9
    );

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "getData", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.GetDataResponse")
    @WebMethod
    public java.lang.String getData(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "setSPlan", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.SetSPlan")
    @ResponseWrapper(localName = "setSPlanResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.SetSPlanResponse")
    @WebMethod
    public java.lang.String setSPlan(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://interfaces.base.snps.osgi.org/")
    @RequestWrapper(localName = "stopSPlan", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.StopSPlan")
    @ResponseWrapper(localName = "stopSPlanResponse", targetNamespace = "http://interfaces.base.snps.osgi.org/", className = "org.platform.sns.StopSPlanResponse")
    @WebMethod
    public java.lang.String stopSPlan(
        @WebParam(name = "arg0", targetNamespace = "http://interfaces.base.snps.osgi.org/")
        java.lang.String arg0
    );
}
