
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.platform.sns;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Jul 26 11:49:08 CEST 2013
 * Generated source version: 2.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "iWebIntegrationInterface",
                      portName = "iWebIntegrationInterfacePort",
                      targetNamespace = "http://interfaces.base.snps.osgi.org/",
                      wsdlLocation = "http://10.31.127.154:9090/wii?wsdl",
                      endpointInterface = "org.platform.sns.IWebIntegrationInterfacePortType")
                      
public class IWebIntegrationInterfacePortTypeImpl implements IWebIntegrationInterfacePortType {

    private static final Logger LOG = Logger.getLogger(IWebIntegrationInterfacePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#sayhello(*
     */
    public java.lang.String sayhello() { 
        LOG.info("Executing operation sayhello");
        try {
            java.lang.String _return = "_return-2119839383";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#buildVirtualSensor(org.platform.sns.ArrayOfString  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String buildVirtualSensor(org.platform.sns.ArrayOfString arg0,java.lang.String arg1) { 
        LOG.info("Executing operation buildVirtualSensor");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1987613997";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#sendCommand(java.lang.String  arg0 ,)org.platform.sns.ArrayOfString  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String sendCommand(java.lang.String arg0,org.platform.sns.ArrayOfString arg1,java.lang.String arg2) { 
        LOG.info("Executing operation sendCommand");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return-1086078711";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#discoverySensorsAndMeasurements(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 ,)java.lang.String  arg7 ,)java.lang.String  arg8 ,)java.lang.String  arg9 )*
     */
    public java.lang.String discoverySensorsAndMeasurements(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6,java.lang.String arg7,java.lang.String arg8,java.lang.String arg9) { 
        LOG.info("Executing operation discoverySensorsAndMeasurements");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        System.out.println(arg9);
        try {
            java.lang.String _return = "_return1612552958";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#getData(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String getData(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getData");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return1476463431";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#setSPlan(java.lang.String  arg0 )*
     */
    public java.lang.String setSPlan(java.lang.String arg0) { 
        LOG.info("Executing operation setSPlan");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-2057947254";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.platform.sns.IWebIntegrationInterfacePortType#stopSPlan(java.lang.String  arg0 )*
     */
    public java.lang.String stopSPlan(java.lang.String arg0) { 
        LOG.info("Executing operation stopSPlan");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1978134484";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
