
/*
 * 
 */

package org.platform.sns;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Jul 26 11:49:08 CEST 2013
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "iWebIntegrationInterface", 
                  wsdlLocation = "http://localhost:9090/wii?wsdl",
                  targetNamespace = "http://interfaces.base.snps.osgi.org/") 
public class IWebIntegrationInterface extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://interfaces.base.snps.osgi.org/", "iWebIntegrationInterface");
    public final static QName IWebIntegrationInterfacePort = new QName("http://interfaces.base.snps.osgi.org/", "iWebIntegrationInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/wii?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9090/wii?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IWebIntegrationInterface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IWebIntegrationInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWebIntegrationInterface() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IWebIntegrationInterfacePortType
     */
    @WebEndpoint(name = "iWebIntegrationInterfacePort")
    public IWebIntegrationInterfacePortType getIWebIntegrationInterfacePort() {
        return super.getPort(IWebIntegrationInterfacePort, IWebIntegrationInterfacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebIntegrationInterfacePortType
     */
    @WebEndpoint(name = "iWebIntegrationInterfacePort")
    public IWebIntegrationInterfacePortType getIWebIntegrationInterfacePort(WebServiceFeature... features) {
        return super.getPort(IWebIntegrationInterfacePort, IWebIntegrationInterfacePortType.class, features);
    }

}
